# Generated by Django 5.2.3 on 2025-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='category',
            field=models.CharField(max_length=200, null=True, verbose_name='دسته بندی دارو'),
        ),
        migrations.AddField(
            model_name='drugs',
            name='date_in_warehouse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ورود دارو به انبار'),
        ),
        migrations.AddField(
            model_name='drugs',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات برای این دارو'),
        ),
        migrations.AddField(
            model_name='drugs',
            name='expiration_date',
            field=models.DateTimeField(null=True, verbose_name='تاریخ انقضا دارو'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='number',
            field=models.CharField(max_length=200, verbose_name='تعداد دارو'),
        ),
    ]
