# Generated by Django 5.2.3 on 2025-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_module', '0003_drugs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='دسته بندی دارو'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='date_in_warehouse',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ورود دارو به انبار'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا دارو'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='number',
            field=models.PositiveIntegerField(verbose_name='تعداد دارو'),
        ),
    ]
