# Generated by Django 5.2.3 on 2025-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_module', '0004_alter_drugs_category_alter_drugs_date_in_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='date_in_warehouse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تاریخ ورود دارو به انبار'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تاریخ انقضا دارو'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='number',
            field=models.CharField(max_length=200, verbose_name='تعداد دارو'),
        ),
    ]
