# Generated by Django 5.2.3 on 2025-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_module', '0006_alter_drugs_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا دارو'),
        ),
    ]
