# Generated by Django 5.2.3 on 2025-07-24 08:18

# import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daysale_module', '0001_initial'),
    ]
    #
    # operations = [
    #     migrations.AlterField(
    #         model_name='dailysale',
    #         name='date',
    #         field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ امروز'),
    #     ),
    # ]
