# Generated by Django 5.2.3 on 2025-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daysale_module', '0002_alter_dailysale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='date',
            field=models.CharField(null=True, verbose_name='تاریخ امروز'),
        ),
    ]
