# Generated by Django 5.2.3 on 2025-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
            ],
            options={
                'verbose_name': 'کد تأیید',
                'verbose_name_plural': 'کدهای تأیید',
            },
        ),
    ]
