# Generated by Django 5.2.3 on 2025-07-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
