# Generated by Django 5.2.3 on 2025-07-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_delete_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_registration_code',
            field=models.BooleanField(default=False),
        ),
    ]
