# Generated by Django 5.2.3 on 2025-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_passwordresetcode_is_registration_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='is_registration_code',
        ),
        migrations.AddField(
            model_name='user',
            name='is_registration_code',
            field=models.BooleanField(default=False),
        ),
    ]
