# Generated by Django 5.2.3 on 2025-07-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_remove_user_is_registration_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='is_registration_code',
        ),
    ]
